export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_PLALISTS: "SET_PLALISTS",
    SET_USER:"SET_USER",
    SET_PLALIST:"SET_PLALIST",
    SET_PLAYING:"SET_PLAYING",
    SET_PLAYER_STATE:"SET_PLAYER_STATE",
    SET_PLAYLIST_ID:"SET_PLAYLIST_ID",
    SET_PLAY_ARTIST:"SET_PLAY_ARTIST",
    SET_ARTIST_ID:"SET_ARTIST_ID",
    SET_ARTIST_DATA:"SET_ARTIST_DATA",
    SET_TOKEN_VALIDATION:"SET_TOKEN_VALIDATION",
    SET_ARTIST_UNIQUE_COLOR:"SET_ARTIST_UNIQUE_COLOR",
     
}